export const resourceGroups = [
  {
    id: 'admin',
    label: 'Admin',
    resources: [
      {
        id: 'clients',
        title: 'Clients',
        endpoint: '/admin/clients',
        write: {
          createLabel: 'New Client',
          canEdit: true,
          statusActions: {
            field: 'isActive',
            activeValue: true,
            activateLabel: 'Activate',
            suspendLabel: 'Suspend',
          },
          fields: [
            ['name', 'Name', 'text', true],
            ['contact_email', 'Contact Email', 'email', false],
            ['is_active', 'Active', 'checkbox', false],
          ],
        },
        columns: [
          ['name', 'Client'],
          ['slug', 'Slug'],
          ['contactEmail', 'Contact'],
          ['isActive', 'Active'],
          ['createdAt', 'Created'],
        ],
      },
      {
        id: 'domains',
        title: 'Domains',
        endpoint: '/admin/domains',
        write: {
          createLabel: 'New Domain',
          canEdit: true,
          fields: [
            ['client_id', 'Client', 'client-select', true],
            ['domain', 'Domain', 'text', true],
            ['status', 'Status', 'select', true, ['pending', 'active']],
          ],
        },
        columns: [
          ['domain', 'Domain'],
          ['clientName', 'Client'],
          ['status', 'Status'],
          ['createdAt', 'Created'],
        ],
      },
      {
        id: 'accounts',
        title: 'Email Accounts',
        endpoint: '/admin/email-accounts',
        write: {
          createLabel: 'New Account',
          canEdit: true,
          fields: [
            ['client_id', 'Client', 'client-select', true],
            ['domain_id', 'Domain', 'option-select', true, { source: 'domains' }],
            ['email', 'Email', 'email', true],
            ['from_name', 'From Name', 'text', false],
            ['smtp_host', 'SMTP Host', 'text', true],
            ['smtp_port', 'SMTP Port', 'number', true],
            ['smtp_encryption', 'SMTP Encryption', 'select', true, ['starttls', 'ssl', 'none']],
            ['smtp_username', 'SMTP Username', 'text', true],
            ['smtp_password', 'SMTP Password', 'password', false],
            ['is_active', 'Active', 'checkbox', false, true],
            ['inbox_enabled', 'Inbox Enabled', 'checkbox', false, false],
            ['imap_host', 'IMAP Host', 'text', false],
            ['imap_port', 'IMAP Port', 'number', false],
            ['imap_encryption', 'IMAP Encryption', 'select', false, ['ssl', 'starttls', 'none']],
            ['imap_username', 'IMAP Username', 'text', false],
            ['imap_password', 'IMAP Password', 'password', false],
          ],
        },
        columns: [
          ['email', 'Email'],
          ['fromName', 'From Name'],
          ['clientName', 'Client'],
          ['domain', 'Domain'],
          ['smtpHost', 'SMTP'],
          ['inboxEnabled', 'Inbox'],
          ['lastVerifiedAt', 'Verified'],
        ],
      },
      {
        id: 'templates',
        title: 'Email Templates',
        endpoint: '/admin/email-templates',
        write: {
          createLabel: 'New Template',
          canEdit: true,
          fields: [
            ['client_id', 'Client', 'client-select', true],
            ['key', 'Key', 'text', true],
            ['name', 'Name', 'text', true],
            ['subject', 'Subject', 'text', true],
            ['type', 'Type', 'select', true, ['communication', 'marketing']],
            ['is_active', 'Active', 'checkbox', false],
            ['body_html', 'HTML Body', 'textarea', true],
            ['body_text', 'Text Body', 'textarea', false],
          ],
        },
        columns: [
          ['name', 'Name'],
          ['key', 'Key'],
          ['subject', 'Subject'],
          ['type', 'Type'],
          ['clientName', 'Client'],
          ['isActive', 'Active'],
        ],
      },
      {
        id: 'api-keys',
        title: 'API Keys',
        endpoint: '/admin/api-keys',
        write: {
          createLabel: 'New API Key',
          canEdit: true,
          canRegenerate: true,
          fields: [
            ['client_id', 'Client', 'client-select', true],
            ['name', 'Name', 'text', true],
            ['abilities', 'Abilities', 'checkbox-group', true, ['send', 'templates', 'inbox']],
            ['is_active', 'Active', 'checkbox', false],
          ],
        },
        columns: [
          ['name', 'Name'],
          ['keyPrefix', 'Prefix'],
          ['clientName', 'Client'],
          ['abilities', 'Abilities'],
          ['isActive', 'Active'],
          ['lastUsedAt', 'Last Used'],
        ],
      },
      {
        id: 'users',
        title: 'Users',
        endpoint: '/admin/users',
        write: {
          createLabel: 'New User',
          canEdit: true,
          statusActions: {
            field: 'status',
            activeValue: 'active',
            activateLabel: 'Activate',
            suspendLabel: 'Suspend',
          },
          fields: [
            ['name', 'Name', 'text', true],
            ['email', 'Email', 'email', true],
            ['password', 'Password', 'password', false],
            ['role', 'Role', 'select', true, ['client_user', 'admin']],
            ['client_id', 'Client', 'client-select', false],
            ['status', 'Status', 'select', true, ['active', 'suspended']],
            ['permissions', 'Permissions', 'checkbox-group', false, ['send_emails', 'view_inbox', 'view_logs', 'manage_templates', 'manage_accounts', 'manage_marketing']],
            ['default_email_template_id', 'Default Template', 'option-select', false, { source: 'emailTemplates' }],
            ['email_account_ids', 'Email Accounts', 'option-multi', false, { source: 'emailAccounts' }],
          ],
        },
        columns: [
          ['name', 'Name'],
          ['email', 'Email'],
          ['clientName', 'Client'],
          ['role', 'Role'],
          ['status', 'Status'],
          ['permissions', 'Permissions'],
          ['lastAccessAt', 'Last Access'],
        ],
      },
    ],
  },
  {
    id: 'messaging',
    label: 'Messaging',
    resources: [
      {
        id: 'inbox',
        title: 'Inbox',
        endpoint: '/inbox/messages',
        inboxActions: true,
        columns: [
          ['subject', 'Subject'],
          ['fromEmail', 'From'],
          ['toEmail', 'To'],
          ['clientName', 'Client'],
          ['mailboxType', 'Mailbox'],
          ['openedAt', 'Opened'],
          ['receivedAt', 'Received'],
        ],
      },
    ],
  },
  {
    id: 'marketing',
    label: 'Marketing',
    resources: [
      {
        id: 'audiences',
        title: 'Audiences',
        endpoint: '/marketing/audiences',
        write: {
          createLabel: 'New Audience',
          fields: [
            ['name', 'Name', 'text', true],
            ['description', 'Description', 'textarea', false],
          ],
        },
        columns: [
          ['name', 'Audience'],
          ['clientName', 'Client'],
          ['contactCount', 'Contacts'],
          ['campaignCount', 'Campaigns'],
          ['source', 'Source'],
          ['createdAt', 'Created'],
        ],
      },
      {
        id: 'campaigns',
        title: 'Campaigns',
        endpoint: '/marketing/campaigns',
        detail: true,
        write: {
          createLabel: 'New Campaign',
          fields: [
            ['client_id', 'Client', 'client-select', true],
            ['email_account_id', 'Sender', 'option-select', true, { source: 'marketingSenders' }],
            ['email_template_id', 'Marketing Template', 'option-select', false, { source: 'marketingTemplates' }],
            ['name', 'Name', 'text', true],
            ['subject', 'Subject', 'text', true],
            ['audience_ids', 'Audiences', 'option-multi', true, { source: 'audiences' }],
            ['recipient_tag', 'Recipient Tag', 'text', false],
            ['body', 'Message Body', 'textarea', false],
            ['template_data_json', 'Template Data JSON', 'textarea', false],
            ['attachments', 'Attachments', 'file-multi', false],
          ],
        },
        columns: [
          ['name', 'Campaign'],
          ['subject', 'Subject'],
          ['clientName', 'Client'],
          ['status', 'Status'],
          ['totalRecipients', 'Recipients'],
          ['sentCount', 'Sent'],
          ['failedCount', 'Failed'],
        ],
      },
      {
        id: 'lead-runs',
        title: 'Lead Generation',
        endpoint: '/marketing/lead-runs',
        detail: true,
        bulkDelete: true,
        write: {
          createLabel: 'Generate Leads',
          fields: [
            ['client_id', 'Client', 'client-select', true],
            ['prompt', 'Brief', 'textarea', false],
            ['industry', 'Industry', 'text', false],
            ['location', 'Country', 'text', false],
            ['province', 'Province', 'text', false],
            ['target_count', 'Target Count', 'number', false],
            ['keywords', 'Tags / Keywords', 'text', false],
            ['source_data', 'Pasted Business List', 'textarea', false],
          ],
        },
        columns: [
          ['prompt', 'Prompt'],
          ['clientName', 'Client'],
          ['industry', 'Industry'],
          ['location', 'Location'],
          ['status', 'Status'],
          ['discoveredCount', 'Found'],
          ['importedCount', 'Imported'],
          ['createdAt', 'Created'],
        ],
      },
      {
        id: 'prospect-calls',
        title: 'Prospect Calls',
        endpoint: '/marketing/prospect-calls',
        write: {
          createLabel: 'Record Call',
          fields: [
            ['company_name', 'Company', 'text', true],
            ['contact_name', 'Contact', 'text', false],
            ['phone', 'Cell', 'text', false],
            ['email', 'Email', 'email', false],
            ['call_date', 'Call Date', 'date', false],
            ['follow_up_at', 'Follow Up', 'datetime-local', false],
            ['status', 'Status', 'select', true, ['new', 'called', 'follow_up', 'meeting_booked', 'not_interested', 'won', 'lost']],
            ['outcome', 'Outcome', 'text', false],
          ],
        },
        columns: [
          ['companyName', 'Company'],
          ['contactName', 'Contact'],
          ['phone', 'Cell'],
          ['email', 'Email'],
          ['clientName', 'Client'],
          ['status', 'Status'],
          ['followUpAt', 'Follow Up'],
          ['outcome', 'Outcome'],
        ],
      },
      {
        id: 'booking-slots',
        title: 'Calendar Slots',
        endpoint: '/marketing/booking-slots',
        write: {
          createLabel: 'Add Slot',
          fields: [
            ['title', 'Meeting', 'text', false],
            ['starts_at', 'Starts', 'datetime-local', true],
            ['ends_at', 'Ends', 'datetime-local', true],
            ['status', 'Status', 'select', false, ['available', 'blocked']],
            ['location', 'Location', 'text', false],
          ],
        },
        columns: [
          ['title', 'Meeting'],
          ['clientName', 'Client'],
          ['startsAt', 'Starts'],
          ['endsAt', 'Ends'],
          ['status', 'Status'],
          ['location', 'Location'],
          ['bookedBy', 'Booked By'],
        ],
      },
      {
        id: 'booking-appointments',
        title: 'Bookings',
        endpoint: '/marketing/booking-appointments',
        columns: [
          ['name', 'Name'],
          ['email', 'Email'],
          ['phone', 'Cell'],
          ['company', 'Company'],
          ['clientName', 'Client'],
          ['title', 'Meeting'],
          ['startsAt', 'Starts'],
          ['status', 'Status'],
        ],
      },
    ],
  },
];

export function findResource(groupId, resourceId) {
  const group = resourceGroups.find((item) => item.id === groupId) || resourceGroups[0];
  const resource = group.resources.find((item) => item.id === resourceId) || group.resources[0];

  return { group, resource };
}
